image: tiangolo/docker-with-compose

stages:
  - check_docker_exist
  - build_image
  - coverage
  - push
  - push_version

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

check_docker_exist:
  tags:
    - idiap
    - linux
    - docker
    - todo
    - not-for-bob
  stage: check_docker_exist
  script:
    - docker info

build_image:
  tags:
    - idiap
    - linux
    - docker
    - todo
    - not-for-bob
  stage: build_image
  script:
    - docker-compose build
coverage:
  tags:
    - idiap
    - linux
    - docker
    - todo
    - not-for-bob
  stage: coverage
  script:
    - echo $CI_JOB_TOKEN | docker login docker.idiap.ch -u gitlab-ci-token --password-stdin
    - docker-compose up -d
    - ./docker_run_tests.sh
    - docker-compose down
push:
  tags:
    - idiap
    - linux
    - docker
    - todo
    - not-for-bob
  stage: push
  only:
    - master
  script:
    - echo $CI_JOB_TOKEN | docker login docker.idiap.ch -u gitlab-ci-token --password-stdin
    - docker push docker.idiap.ch/wenet/personal_context_builder:latest
    - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
    - docker tag docker.idiap.ch/wenet/personal_context_builder:latest internetofus/personal-context-builder:latest
    - docker push internetofus/personal-context-builder:latest
push_version:
  tags:
    - idiap
    - linux
    - docker
    - todo
    - not-for-bob
  stage: push_version
  only:
    - tags
  script:
    - echo $CI_JOB_TOKEN | docker login docker.idiap.ch -u gitlab-ci-token --password-stdin
    - docker tag  docker.idiap.ch/wenet/personal_context_builder:latest docker.idiap.ch/wenet/personal_context_builder:$CI_COMMIT_TAG
    - docker push docker.idiap.ch/wenet/personal_context_builder:$CI_COMMIT_TAG
    - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
    - docker tag docker.idiap.ch/wenet/personal_context_builder:$CI_COMMIT_TAG internetofus/personal-context-builder:$CI_COMMIT_TAG
    - docker push internetofus/personal-context-builder:$CI_COMMIT_TAG
