 before_script:
   - docker info

 build_image:
   script:
     - docker-compose build
 coverage:
   script:
     - docker-compose up -d
     - ./docker_run_tests.sh
     - docker-compose down
 push:
  only:
     - master
  script:
     - echo $CI_PUSH_TOKEN | docker login docker.idiap.ch -u wdroz --password-stdin
     - docker tag  docker.idiap.ch/wenet/personal_context_builder:$CI_COMMIT_SHA  docker.idiap.ch/wenet/personal_context_builder:latest
     - docker push docker.idiap.ch/wenet/personal_context_builder:latest