 stages:
   - check_docker_exist
   - build_image
   - coverage
   - push
   - push_version

 check_docker_exist:
   stage: check_docker_exist
   script:
     - docker info

 build_image:
   stage: build_image
   script:
     - docker-compose build
 coverage:
   stage: coverage
   script:
     - docker-compose up -d
     - ./docker_run_tests.sh
     - docker-compose down
 push:
  stage: push
  only:
     - master
  script:
     - echo $CI_JOB_TOKEN | docker login docker.idiap.ch -u gitlab-ci-token --password-stdin
     - docker push docker.idiap.ch/wenet/personal_context_builder:latest
 push_version:
  stage: push_version
  only:
     - tags
  script:
     - echo $CI_JOB_TOKEN | docker login docker.idiap.ch -u gitlab-ci-token --password-stdin
     - docker tag  docker.idiap.ch/wenet/personal_context_builder:latest docker.idiap.ch/wenet/personal_context_builder:$CI_COMMIT_TAG
     - docker push docker.idiap.ch/wenet/personal_context_builder:$CI_COMMIT_TAG
