# Profile manager

### get users
GET https://wenet.u-hopper.com/dev/profile_manager/userIdentifiers?offset=0&limit=100 HTTP/1.1
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv DEVSECRET}}



### get specific user

GET https://wenet.u-hopper.com/dev/profile_manager/profiles/35 HTTP/1.1
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv DEVSECRET}}


# Streambase


### get user 12

GET https://wenet.u-hopper.com/dev/streambase/data?from=20211109&to=20211109&properties=locationeventpertime&userId=12
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv DEVSECRET}}
