# Personal context builder

GET https://lab.idiap.ch/devel/hub/wenet/closest/?latitude=1&longitude=1&nb_user_max=10 HTTP/1.1
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv DEVSECRET}}

# Profile manager

### get users
GET https://wenet.u-hopper.com/dev/profile_manager/userIdentifiers?offset=0&limit=100000 HTTP/1.1
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv DEVSECRET}}



### get specific user

GET https://wenet.u-hopper.com/dev/profile_manager/profiles/35 HTTP/1.1
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv DEVSECRET}}


# Streambase


### get user 12

GET https://wenet.u-hopper.com/dev/streambase/data?from=20211109&to=20211109&properties=locationeventpertime&userId=12
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv DEVSECRET}}

### get user 12 recent

GET https://wenet.u-hopper.com/dev/streambase/data?from=20220607&to=20220607&properties=locationeventpertime&userId=12
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv DEVSECRET}}

### get user 12 directly

GET http://streambase4.disi.unitn.it:8190/data?from=20211109&to=20211109&properties=locationeventpertime&userId=12
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv DEVSECRET}}

### get user 12 directly on old server

GET http://streambase1.disi.unitn.it:8190/data?from=20211109&to=20211109&properties=locationeventpertime&userId=12
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv DEVSECRET}}


### start generator

POST http://streambase4.disi.unitn.it:8190/generator/start
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv DEVSECRET}}

### stop generator

POST http://streambase4.disi.unitn.it:8190/generator/stop
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv DEVSECRET}}