version: '3'
services:
  wenet-redis:
    restart: always
    container_name: wenet-redis
    image: "redis:5.0-alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
     - wenet-redis-data:/data
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
  wenet-realtime-redis:
    restart: always
    container_name: wenet-realtime-redis
    image: "redis:5.0-alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
     - wenet-realtime-redis-data:/data
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
  wenet-api:
    restart: always
    build: .
    container_name: wenet-api
    env_file:
      - wenet.env
    ports:
     - "8081:80"
    volumes:
     - wenet-data:/data
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
    image:  'docker.idiap.ch/wenet/personal_context_builder:v0.1.0'
networks:
  default:
    external:
      name: docker1

volumes:
  wenet-redis-data:
  wenet-realtime-redis-data:
  wenet-data:
