apiVersion: apps/v1
kind: Deployment
metadata:
  name: wenet-updater-deployment
  labels:
    app: wenet
spec:
  selector:
    matchLabels:
      app: wenet
  replicas: 3
  template:
    metadata:
      labels:
        app: wenet
    spec:
      containers:
        - env:
            # Should use secret, but don't have time to dive into it
            - name: PCB_WENET_API_KEY
              value: { { REDACTED } }
            - name: PCB_USER_LOCATION_URL
              value: http://wenet/users_locations/
            - name: PYTHONUNBUFFERED
              value: "0"
            - name: PCB_LOGGER_LEVEL
              value: "20"
          name: wenet-personal-context-builder
          image: docker.idiap.ch/wenet/personal_context_builder:latest
          volumeMounts:
            - name: tz-zurich
              mountPath: /etc/localtime
          command: ["python"]
          args:
            [
              "-m",
              "personal_context_builder.wenet_cli_entrypoint",
              "--update_realtime",
            ]
          resources:
            limits:
              memory: 10Gi
              #cpu: "2"
            requests:
              memory: 10Gi
              #cpu: "2"
      imagePullSecrets:
        - name: wenet-realtime-secret
      volumes:
        - name: tz-zurich
          hostPath:
            path: /usr/share/zoneinfo/Europe/Zurich
