apiVersion: apps/v1
kind: Deployment
metadata:
  name: wenet-updater-deployment
  labels:
    app: wenet
spec:
  selector:
    matchLabels:
      app: wenet
  replicas: 1
  template:
    metadata:
      labels:
        app: wenet
    spec:
      containers:
        - name: wenet-personal-context-builder
          image: docker.idiap.ch/wenet/personal_context_builder:latest
          envFrom:
            - configMapRef:
                name: settings-wenet-env
          volumeMounts:
            - name: tz-zurich
              mountPath: /etc/localtime
          command: ["python"]
          args:
            [
              "-m",
              "personal_context_builder.wenet_cli_entrypoint",
              "--update_realtime",
            ]
          resources:
            limits:
              memory: 10Gi
              #cpu: "2"
            requests:
              memory: 10Gi
              #cpu: "2"
      imagePullSecrets:
        - name: wenet-realtime-secret
      volumes:
        - name: tz-zurich
          hostPath:
            path: /usr/share/zoneinfo/Europe/Zurich

---
apiVersion: v1
data:
  PCB_WENET_API_KEY: REDACTED
  PCB_USER_LOCATION_URL: http://wenet/users_locations/
  PYTHONUNBUFFERED: "0"
  PCB_LOGGER_LEVEL: "20"
  PCB_WENET_SENTRY_KEY: "REDACTED"
kind: ConfigMap
metadata:
  name: settings-wenet-env
