# Personal context builder

GET https://internetofus.u-hopper.com/prod/realtime_api/closest/?latitude=1&longitude=1&nb_user_max=10 HTTP/1.1
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv PRODSECRET}}

# Profile manager

### get users
GET https://internetofus.u-hopper.com/prod/profile_manager/userIdentifiers?offset=0&limit=100 HTTP/1.1
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv PRODSECRET}}



### get specific user

GET https://internetofus.u-hopper.com/prod/profile_manager/profiles/12 HTTP/1.1
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv PRODSECRET}}


# Streambase


### get user 12

GET https://internetofus.u-hopper.com/prod/streambase/data?from=20220930&to=20220930&properties=locationeventpertime&userId=44
Authorization: test:wenet
Accept: application/json
x-wenet-component-apikey: {{$dotenv PRODSECRET}}